  name: Auto Update sub.txt

on:
  schedule:
    - cron: '0 3 * * *' # 每天凌晨 3 点自动更新
  workflow_dispatch: # 允许手动触发
  push:
    paths:
      - 'update.py' # 如果未来加自动更新脚本，push update.py 也会触发

jobs:
  update-sub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update sub.txt (manual example)
        run: |
          echo "更新时间：$(date)" > sub.txt
          echo "vless://106a7bb5-3a6a-413b-b803-1280cf988eb2@23.94.136.9:63422?encryption=none&flow=xtls-rprx-vision&security=reality&sni=www.cloudflare.com&fp=chrome&pbk=8Uiw0-x-P1vTuq77lJS4X2sWOSa5lNdOA1qY3PRlx2E&type=tcp&headerType=none#233boy-tcp-23.94.136.9" >> sub.txt
          echo "vless://df1c9fd2-761f-42d0-a23b-c908b2b4d746@wss.hangzhou9vpn.top:443?encryption=none&security=tls&type=ws&host=wss.hangzhou9vpn.top&path=%2Fdf1c9fd2-761f-42d0-a23b-c908b2b4d746#233boy-ws-wss.hangzhou9vpn.top" >> sub.txt

      - name: Commit & Push changes
        run: |
          git config --global user.email "jzrqs@users.noreply.github.com"
          git config --global user.name "DrRen Bot"
          git add sub.txt
          git commit -m "自动更新 sub.txt [skip ci]" || echo "No changes to commit"
          git push
